Update to 0.10.0beta5:
digiKam 0.10.0-beta5 - Release date: 2008-10-26

IMPORTANT: This is a beta release : do not use yet in production !!!
====================================================================

NEW FEATURES:

General        : digiKam can be compiled natively under Microsoft Windows.
General        : libkdcraw dependency updated to 0.4.0
General        : libgphoto2 dependency is now optional to be able to compile digiKam under operating systems
                 not supported by GPhoto2

001 ==> 171953 : Using create "Date-based sub-albums" makes import fail.
002 ==> 118318 : Make (lib)gphoto support a configure flag.
003 ==> 172269 : digiKam hangs for around 20-60 seconds when starting.
004 ==> 172648 : Thumbnail click does not display embedded picture preview.
005 ==> 172650 : No kipi plugins available.
006 ==> 172651 : Send image by email missing.
007 ==> 168005 : Week view broken in timeline.
008 ==> 172295 : digiKam has a hard dependency on Jasper library.
009 ==> 172733 : Crash on Synchronize images with database.
010 ==> 172776 : Combine Edit and Album menus, and other ideas.
011 ==> 172836 : No menu item for lensfun.
012 ==> 172912 : "Slide" becomes "Slideshow" text on button in Main window.
013 ==> 172882 : Setup verbiage patches.
014 ==> 172884 : Welcome/First-Run verbiage patches.
015 ==> 172892 : Tips verbiage changes.
016 ==> 172895 : Setup verbiage patches for slideshow and albumview.
017 ==> 172898 : Verbiage changes for Util-ImageEditor-ImageResize.cpp.
018 ==> 172899 : Verbiage changes for digikamapp.cpp.
019 ==> 167320 : Filmstrip in album view is not synchronized correctly.
020 ==> 172911 : Album File lister does not have an "All Image Files" filter.
021 ==> 167777 : Thumbnails in Album not shown at first start of digiKam.

digiKam 0.10.0-beta4 - Release date: 2008-10-02

IMPORTANT: This is a beta release : do not use yet in production !!!
====================================================================

NEW FEATURES:

BUGFIXES FROM KDE BUGZILLA (alias B.K.O | http://bugs.kde.org):

001 ==> 169814 : Compilation error: no exp2().
002 ==> 165345 : Selecting images from bottom right to top left does not work.
003 ==> 170693 : Enable geotagging of Olympus orf images.
004 ==> 170711 : Write single Keywords instead of Hierarchy into IPTC.
005 ==> 168569 : New Album Folders are not detected in displayed in GUI until restart.
006 ==> 165337 : Text overlapping box on welcome page.
007 ==> 171310 : No preview photos shown clicking on imported albums.
008 ==> 171778 : digiKam does not load photos in its database.
009 ==> 171736 : Make transferring of metadata between machines easier.
010 ==> 170929 : Compilation of SVN version fails with gcc 4.3.2 unless debug option is activated.
011 ==> 171989 : Can't set GPS photo location on .nef images.
012 ==> 172018 : Initial cursor in the "sharpen" dialog is on the "cancel" button.
013 ==> 172033 : Unable to draw rectangle from right to left.

digiKam 0.10.0-beta3 - Release date: 2008-09-03

IMPORTANT: This is a beta release : do not use yet in production !!!
====================================================================

NEW FEATURES:

General        : libkdcraw dependency updated to 0.3.0
General        : Raw metadata can be edited, changed, added to TIFF/EP like RAW file formats (require Exiv2 >= 0.18).
                 Currently DNG, NEF, and PEF raw files are supported. More will be added in the future.

Image Editor   : All image plugin tool settings provide default buttons to reset values.
Image Editor   : New Raw import tool to handle Raw pictures with customized decoding settings.
Image Editor   : All image plugin dialogs are removed. All tools are embedded in editor window.

BUGFIXES FROM KDE BUGZILLA (alias B.K.O | http://bugs.kde.org):

001 ==> 166310 : Preview not working in image effect dialogs.
002 ==> 167571 : Unnatural order when removing images from light table.
003 ==> 167139 : Crash if Exif.GPSInfo.GPSAltitude is empty.
004 ==> 167778 : Assigning ratings in image editor via shortcuts or toolbar not working.
005 ==> 168567 : Unable to edit or remove IPTC and XMP info.
006 ==> 168846 : crash after playing with tags (seems to be rather a crash in Qt or kdelibs).
007 ==> 166671 : Image filter dialog buttons are much too big.
008 ==> 134486 : Keywords are not written to raw files even though they do embed iptc/exif.
009 ==> 168839 : Digikam crashed after tagging.
010 ==> 167085 : Color selection in sketch search tool looks plain black.
011 ==> 168852 : Crash on profile application.
012 ==> 167867 : Album view is reset by changing settings.
013 ==> 168461 : Info in Properties panel not updated after moving to other image.
014 ==> 169704 : Crash during RAW import.
015 ==> 166437 : Deleting images in Image Editor not working properly.