Update SARG to latest stable release (2.0.2). List of changes:
	- grepday with invalid font path;
	- -v option added to display Sarg version on console;
	- Segmenation fault caused by an unclosed file;
	- SquidGuard log formats added;
	- time field added to topsites report;
	- fixtime function with wrong definition, changed to long long;
	- Solaris 9 compiling error: error: conflicting types for 'my_mkdir';
	- segfaults if the denied report is disabled in sarg.conf;
	- improved reading performance;
	- Russian sarg-php translation added.

This package changes:

	- rebuild ./configure script in way to normal C compiler detection;
	- rearrange a make targets in a build order.