Fix perl path in included nasm wrapper. Remove unnecessary header include that breaks build on NetBSD.
Still fails to build with:
thread.C: In member function 'int Thread::get_tid()':
thread.C:242: error: cast from '__pthread_st*' to 'int' loses precision